name: .NET CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Lint using dotnet format
      run: dotnet format --verify-no-changes --severity warn || true

    - name: Build the project
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release --verbosity normal

    - name: Security check - Vulnerable packages
      run: dotnet list package --vulnerable || true

    - name: Simulate Deploy - Copy files to "build-output"
      run: |
        mkdir -p build-output
        cp -r bin/Release/net8.0/* build-output/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: build-output/
